### ISSUE TITLE
Data Overwritten

### ISSUE THREAD

**Issue by abartolo-912** [kathleenleeper/open-access-representation#7]
ok idiots, I think someone at some point overwrote data in the parsed_oai.csv file. My RGender column is gone and some of the old NA values are back in place of "unknowns" which messed up our graphs. The script I wrote is dependent on the csv file looking a certain way so if you add more data you should append it to the data frame or at least be aware of not overwriting data.

**Comment by abartolo-912** [comment]
How do I assign Kat? They're guilty as well.

**Comment by abartolo-912** [comment]
Lastly, what do we do about NGender's "misparsed" column? Can I safely turn those into "unknowns"?

**Comment by kathleenleeper** [comment]
I no longer feel bad at all. The file our python code writes to is parsed-oai.csv, so anytime we make the code better that file is gonna be overwritten. We can write to a different file name in the future, but probably best bet is to have an R script that automatically cleans up our output for you

**Comment by kathleenleeper** [comment]
And yeah, feel free to change misparsed or remove those rows completely.

**Comment by abartolo-912** [comment]
wait, it's not possible to **not** overwrite the file every single time? God python is dumb. I guess I could re-run a portion of our script to keep adding my RGender column every single time we create a graph or output but that doesn't sound practical... Especially considering we might want to make direct and complex comparisons of each gender assigner.

Then maybe its best that you hand the file over to me when you're "done" so that I can add my column last and then we can do stuff?

**Comment by abartolo-912** [comment]
KAT THIS ISSUE IS NOT CLOSED

**Comment by abartolo-912** [comment]
IT IS VERY OPEN
